version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: api_backend
        container_name: api_backend-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - .:/var/www
        networks:
            - api_backend

    db:
        image: mysql:5.7
        container_name: api_backend-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: api_backend_db
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_PASSWORD: 12345
            MYSQL_USER: docker_user
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/mysql/data_db:/var/lib/mysql
        networks:
            - api_backend

    nginx:
        image: nginx:alpine
        container_name: api_backend-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - .:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - api_backend

networks:
    api_backend:
        driver: bridge
#https://www.digitalocean.com/community/tutorials/how-to-install-and-set-up-laravel-with-docker-compose-on-ubuntu-20-04-es
